/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  publishedAt?: string;
  spanish?: {
    title?: string;
    excerpt?: string;
    body?: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          image?: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          };
          alt?: string;
          caption?: string;
          credit?: string;
          creditUrl?: string;
          _type: "articleImage";
          _key: string;
        }
    >;
  };
  english?: {
    title?: string;
    excerpt?: string;
    body?: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          image?: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          };
          alt?: string;
          caption?: string;
          credit?: string;
          creditUrl?: string;
          _type: "articleImage";
          _key: string;
        }
    >;
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/lib/sanity.ts
// Variable: postSlugsQuery
// Query: *[    _type == "post" &&    !(_id in path("drafts.**")) &&    defined(publishedAt) &&    publishedAt <= now() &&    defined(slug.current) &&    (      ($locale == "es" && defined(spanish.title) && defined(spanish.excerpt) && defined(spanish.body) && count(spanish.body) > 0) ||      ($locale == "en" && defined(english.title) && defined(english.excerpt) && defined(english.body) && count(english.body) > 0)    )  ]{ "slug": slug.current }
export type PostSlugsQueryResult = Array<{
  slug: string | null;
}>;

// Source: ../web/src/lib/sanity.ts
// Variable: postsQuery
// Query: *[    _type == "post" &&    !(_id in path("drafts.**")) &&    defined(publishedAt) &&    publishedAt <= now() &&    defined(slug.current) &&    (      ($locale == "es" && defined(spanish.title) && defined(spanish.excerpt) && defined(spanish.body) && count(spanish.body) > 0) ||      ($locale == "en" && defined(english.title) && defined(english.excerpt) && defined(english.body) && count(english.body) > 0)    )  ] | order(publishedAt desc){    _id,    "slug": slug.current,    "title": select($locale == "es" => spanish.title, $locale == "en" => english.title),    "excerpt": select($locale == "es" => spanish.excerpt, $locale == "en" => english.excerpt),    publishedAt,    "hasSpanish": defined(spanish.title) && defined(spanish.excerpt) && defined(spanish.body) && count(spanish.body) > 0,    "hasEnglish": defined(english.title) && defined(english.excerpt) && defined(english.body) && count(english.body) > 0  }
export type PostsQueryResult = Array<{
  _id: string;
  slug: string | null;
  title: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  hasSpanish: boolean | false | null;
  hasEnglish: boolean | false | null;
}>;

// Source: ../web/src/lib/sanity.ts
// Variable: postQuery
// Query: *[    _type == "post" &&    !(_id in path("drafts.**")) &&    defined(publishedAt) &&    publishedAt <= now() &&    slug.current == $slug &&    (      ($locale == "es" && defined(spanish.title) && defined(spanish.excerpt) && defined(spanish.body) && count(spanish.body) > 0) ||      ($locale == "en" && defined(english.title) && defined(english.excerpt) && defined(english.body) && count(english.body) > 0)    )  ][0]{    _id,    "slug": slug.current,    "title": select($locale == "es" => spanish.title, $locale == "en" => english.title),    "excerpt": select($locale == "es" => spanish.excerpt, $locale == "en" => english.excerpt),    "body": select($locale == "es" => spanish.body, $locale == "en" => english.body)[]{      ...,      _type == "articleImage" => {        ...,        image {          ...,          "dimensions": asset->metadata.dimensions        }      }    },    publishedAt,    "hasSpanish": defined(spanish.title) && defined(spanish.excerpt) && defined(spanish.body) && count(spanish.body) > 0,    "hasEnglish": defined(english.title) && defined(english.excerpt) && defined(english.body) && count(english.body) > 0  }
export type PostQueryResult = {
  _id: string;
  slug: string | null;
  title: string | null;
  excerpt: string | null;
  body: Array<
    | {
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          dimensions: SanityImageDimensions | null;
        } | null;
        alt?: string;
        caption?: string;
        credit?: string;
        creditUrl?: string;
        _type: "articleImage";
        _key: string;
      }
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
  > | null;
  publishedAt: string | null;
  hasSpanish: boolean | false | null;
  hasEnglish: boolean | false | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[\n    _type == "post" &&\n    !(_id in path("drafts.**")) &&\n    defined(publishedAt) &&\n    publishedAt <= now() &&\n    defined(slug.current) &&\n    (\n      ($locale == "es" && defined(spanish.title) && defined(spanish.excerpt) && defined(spanish.body) && count(spanish.body) > 0) ||\n      ($locale == "en" && defined(english.title) && defined(english.excerpt) && defined(english.body) && count(english.body) > 0)\n    )\n  ]{ "slug": slug.current }': PostSlugsQueryResult;
    '*[\n    _type == "post" &&\n    !(_id in path("drafts.**")) &&\n    defined(publishedAt) &&\n    publishedAt <= now() &&\n    defined(slug.current) &&\n    (\n      ($locale == "es" && defined(spanish.title) && defined(spanish.excerpt) && defined(spanish.body) && count(spanish.body) > 0) ||\n      ($locale == "en" && defined(english.title) && defined(english.excerpt) && defined(english.body) && count(english.body) > 0)\n    )\n  ] | order(publishedAt desc){\n    _id,\n    "slug": slug.current,\n    "title": select($locale == "es" => spanish.title, $locale == "en" => english.title),\n    "excerpt": select($locale == "es" => spanish.excerpt, $locale == "en" => english.excerpt),\n    publishedAt,\n    "hasSpanish": defined(spanish.title) && defined(spanish.excerpt) && defined(spanish.body) && count(spanish.body) > 0,\n    "hasEnglish": defined(english.title) && defined(english.excerpt) && defined(english.body) && count(english.body) > 0\n  }': PostsQueryResult;
    '*[\n    _type == "post" &&\n    !(_id in path("drafts.**")) &&\n    defined(publishedAt) &&\n    publishedAt <= now() &&\n    slug.current == $slug &&\n    (\n      ($locale == "es" && defined(spanish.title) && defined(spanish.excerpt) && defined(spanish.body) && count(spanish.body) > 0) ||\n      ($locale == "en" && defined(english.title) && defined(english.excerpt) && defined(english.body) && count(english.body) > 0)\n    )\n  ][0]{\n    _id,\n    "slug": slug.current,\n    "title": select($locale == "es" => spanish.title, $locale == "en" => english.title),\n    "excerpt": select($locale == "es" => spanish.excerpt, $locale == "en" => english.excerpt),\n    "body": select($locale == "es" => spanish.body, $locale == "en" => english.body)[]{\n      ...,\n      _type == "articleImage" => {\n        ...,\n        image {\n          ...,\n          "dimensions": asset->metadata.dimensions\n        }\n      }\n    },\n    publishedAt,\n    "hasSpanish": defined(spanish.title) && defined(spanish.excerpt) && defined(spanish.body) && count(spanish.body) > 0,\n    "hasEnglish": defined(english.title) && defined(english.excerpt) && defined(english.body) && count(english.body) > 0\n  }': PostQueryResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
